Refactored and redesigned Category Breakdown
CivBuilder/Carbon pull request #104
Opened 2023-04-20 07:42 UTC by adamantisaurus

**Progress Screen**
- Redesigned Category Breakdown section on Progress Screen to take up less space.
- Renamed prior-existing `CategoryChart` component to `CategoryBreakdown`.
- Created new `CategoryChart` component that solely handles the rendering of the category breakdown chart.
- Implemented 2 utility functions to reduce bugs when rendering `CategoryChart`.
- Created new `KeyFactors` component and integrated it into the Category Breakdown section. Note, I have temporarily disabled the feature that compared emissions between months and will reimplement in a future PR.

**Miscellaneous**
- Created a `Section` component that renders a new section on any screen. Intended for use on Home and Progress screens. See Category Breakdown for example.
- Created separate CSS files for some components. Will add more in a later PR.
- Renamed `colors` folder to `styling` which will contain stylesheets and the color palette.
- Added m0ar colors to the palette!

2023-04-20 08:53 UTC, erickserr125 reviewed
This is a huge change! I appreciate that there are new colors to choose from as I was previously struggling with choosing appropriate colors for the questionnaire. I'm not sure that this will yield merge conflicts with the file re-structure, so I'm going to hold on an approval until the other PR's are approved. Then I'll approve once there are no others.

2023-04-20 17:47 UTC, CivBuilder commented on Carbon/navigation/screens/Progress/CategoryChart.js
> +  // const data = [{ "x": "Transport", "y": 50 }, { "x": "Lifestyle", "y": 20 }, { "x": "Home", "y": 10 }, { "x": "Diet", "y": 90 }];
we'll want to delete these commented out lines in the future

2023-04-20 17:48 UTC, CivBuilder approved these changes

2023-04-20 22:57 UTC, mcebaniqued requested changes
Everything looks good! Just need some minor tweaks from what Chris said as well as the button in progress screen. Also make sure to merge the most recent `main` branch. It seems like it's behind by 1. Once they're done, I'll be happy to approve it! 😄

2023-04-20 22:57 UTC, mcebaniqued commented on Carbon/navigation/screens/Progress/ProgressScreen.js
Keep the `Set Goal` button uncommented or remove it completely. We've already migrated it to the `+` button.

2023-04-20 23:02 UTC, mcebaniqued approved these changes

2023-04-20 23:02 UTC, mcebaniqued commented on Carbon/navigation/screens/Progress/ProgressScreen.js
Also if you can, can you remove the `Log` component from Home Screen and put it into Progress Screen right under this chart?

2023-04-20 23:04 UTC, mcebaniqued requested changes

2023-04-20 23:04 UTC, mcebaniqued commented on Carbon/navigation/screens/Progress/ProgressScreen.js
Also if you can, can you remove the `Log` component from Home Screen and put it into Progress Screen right under this chart?

2023-04-21 01:07 UTC, adamantisaurus commented on Carbon/navigation/screens/Progress/ProgressScreen.js
Done!

2023-04-21 01:07 UTC, adamantisaurus commented on Carbon/navigation/screens/Progress/ProgressScreen.js
Done and done!

2023-04-21 01:15 UTC, mcebaniqued approved these changes
Looks good to me! Thanks for making the changes 😄

2023-04-21 01:16 UTC, merged