Goal Setting Refactor - Calculate Pounds of CO2 Cut by Goal %
CivBuilder/Carbon pull request #119
Opened 2023-04-24 22:05 UTC by CivBuilder

This PR allows users to visualize how many pounds of CO2 they'd cut this month based on the goal they are setting.

2023-04-24 22:07 UTC, CivBuilder commented on Server/api/userEmissions.js
> +  [0, 0, 0, 0, 0], // YESTERDAY
Some of these changes aren't actually changes it's just my linter fixing formatting.

2023-04-24 22:22 UTC, erickserr125 approved these changes
Very nice UI and practical improvement to allow users to set clean carbon goals for themselves!

2023-04-25 01:39 UTC, aq6476 requested changes
Hey Chris, I like the feature but came across this visual error if a user has no emissions for the previous month, can it be updated to have a different message in that case? 🙂, I'd recommend maybe just an Enum value to used to show a different message. 
![image](https://user-images.githubusercontent.com/75909971/234153332-079585ae-62d3-46ee-9857-a3e3acdad8db.png)

2023-04-25 01:52 UTC, aq6476 approved these changes

2023-04-25 01:53 UTC, merged